#!/bin/bash
# =============================================================================
# Audiobook Library - System-wide Installation Script
# =============================================================================
# Installs audiobook library as a system service.
#
# Locations:
#   Executables:  /usr/local/bin/audiobooks-*
#   Config:       /etc/audiobooks/
#   Library:      /usr/local/lib/audiobooks/
#   Services:     /etc/systemd/system/
#   Data:         Configurable (default: /srv/audiobooks)
#
# Usage:
#   sudo ./install-system.sh [OPTIONS]
#
# Options:
#   --data-dir PATH    Audiobook data directory (default: /srv/audiobooks)
#   --uninstall        Remove system installation
#   --no-services      Skip systemd service installation
#   --help             Show this help message
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default paths
INSTALL_PREFIX="/usr/local"
CONFIG_DIR="/etc/audiobooks"
LIB_DIR="${INSTALL_PREFIX}/lib/audiobooks"
BIN_DIR="${INSTALL_PREFIX}/bin"
SYSTEMD_DIR="/etc/systemd/system"
DATA_DIR="/srv/audiobooks"

# Script directory (source)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Options
INSTALL_SERVICES=true
UNINSTALL=false

# -----------------------------------------------------------------------------
# Parse arguments
# -----------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-dir)
            DATA_DIR="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        --no-services)
            INSTALL_SERVICES=false
            shift
            ;;
        --help)
            head -30 "$0" | grep -E '^#' | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# -----------------------------------------------------------------------------
# Check root
# -----------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root (sudo)${NC}"
    exit 1
fi

# -----------------------------------------------------------------------------
# Uninstall
# -----------------------------------------------------------------------------
if [[ "$UNINSTALL" == "true" ]]; then
    echo -e "${YELLOW}=== Uninstalling Audiobook Library (System) ===${NC}"

    # Stop and disable services
    systemctl stop audiobooks-api.service audiobooks-web.service 2>/dev/null || true
    systemctl disable audiobooks-api.service audiobooks-web.service 2>/dev/null || true

    # Remove files
    rm -f "${BIN_DIR}/audiobooks-api"
    rm -f "${BIN_DIR}/audiobooks-web"
    rm -f "${BIN_DIR}/audiobooks-scan"
    rm -f "${BIN_DIR}/audiobooks-import"
    rm -rf "${LIB_DIR}"
    rm -f "${SYSTEMD_DIR}/audiobooks-api.service"
    rm -f "${SYSTEMD_DIR}/audiobooks-web.service"
    rm -f "${SYSTEMD_DIR}/audiobooks.target"

    # Reload systemd
    systemctl daemon-reload

    echo -e "${GREEN}Uninstallation complete.${NC}"
    echo "Note: Configuration in ${CONFIG_DIR} and data in ${DATA_DIR} were NOT removed."
    exit 0
fi

# -----------------------------------------------------------------------------
# Install
# -----------------------------------------------------------------------------
echo -e "${GREEN}=== Audiobook Library System Installation ===${NC}"
echo ""
echo "Installation paths:"
echo "  Executables:  ${BIN_DIR}/"
echo "  Config:       ${CONFIG_DIR}/"
echo "  Library:      ${LIB_DIR}/"
echo "  Services:     ${SYSTEMD_DIR}/"
echo "  Data:         ${DATA_DIR}/"
echo ""

# Create directories
echo -e "${BLUE}Creating directories...${NC}"
mkdir -p "${CONFIG_DIR}"
mkdir -p "${LIB_DIR}"
mkdir -p "${DATA_DIR}/Library"
mkdir -p "${DATA_DIR}/Sources"
mkdir -p "${DATA_DIR}/Supplements"
mkdir -p "/var/lib/audiobooks"
mkdir -p "/var/log/audiobooks"

# Install library files
echo -e "${BLUE}Installing library files...${NC}"
cp -r "${SCRIPT_DIR}/library" "${LIB_DIR}/"
cp -r "${SCRIPT_DIR}/lib" "${LIB_DIR}/"
[[ -d "${SCRIPT_DIR}/converter" ]] && cp -r "${SCRIPT_DIR}/converter" "${LIB_DIR}/"
cp "${SCRIPT_DIR}/etc/audiobooks.conf.example" "${CONFIG_DIR}/"

# Create config file if it doesn't exist
if [[ ! -f "${CONFIG_DIR}/audiobooks.conf" ]]; then
    echo -e "${BLUE}Creating configuration file...${NC}"
    cat > "${CONFIG_DIR}/audiobooks.conf" << EOF
# Audiobook Library Configuration
# Generated by install-system.sh on $(date +%Y-%m-%d)

# Data directories
AUDIOBOOKS_DATA="${DATA_DIR}"
AUDIOBOOKS_LIBRARY="\${AUDIOBOOKS_DATA}/Library"
AUDIOBOOKS_SOURCES="\${AUDIOBOOKS_DATA}/Sources"
AUDIOBOOKS_SUPPLEMENTS="\${AUDIOBOOKS_DATA}/Supplements"

# Application directories
AUDIOBOOKS_HOME="${LIB_DIR}"
AUDIOBOOKS_DATABASE="/var/lib/audiobooks/audiobooks.db"
AUDIOBOOKS_COVERS="\${AUDIOBOOKS_HOME}/library/web-v2/covers"
AUDIOBOOKS_CERTS="\${AUDIOBOOKS_HOME}/library/certs"
AUDIOBOOKS_LOGS="/var/log/audiobooks"
AUDIOBOOKS_VENV="\${AUDIOBOOKS_HOME}/library/venv"

# Server settings
AUDIOBOOKS_API_PORT="5001"
AUDIOBOOKS_WEB_PORT="8090"
AUDIOBOOKS_BIND_ADDRESS="0.0.0.0"
AUDIOBOOKS_HTTPS_ENABLED="true"
EOF
fi

# Create wrapper scripts in /usr/local/bin
echo -e "${BLUE}Creating executable wrappers...${NC}"

# API server wrapper
cat > "${BIN_DIR}/audiobooks-api" << 'EOF'
#!/bin/bash
# Audiobook Library API Server
source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
exec "$(audiobooks_python)" "${AUDIOBOOKS_HOME}/library/backend/api.py" "$@"
EOF
chmod 755 "${BIN_DIR}/audiobooks-api"

# Web server wrapper
cat > "${BIN_DIR}/audiobooks-web" << 'EOF'
#!/bin/bash
# Audiobook Library Web Server (HTTPS)
source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
exec python3 "${AUDIOBOOKS_HOME}/library/web-v2/https_server.py" "$@"
EOF
chmod 755 "${BIN_DIR}/audiobooks-web"

# Scanner wrapper
cat > "${BIN_DIR}/audiobooks-scan" << 'EOF'
#!/bin/bash
# Audiobook Library Scanner
source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
exec "$(audiobooks_python)" "${AUDIOBOOKS_HOME}/library/scanner/scan_audiobooks.py" "$@"
EOF
chmod 755 "${BIN_DIR}/audiobooks-scan"

# Database import wrapper
cat > "${BIN_DIR}/audiobooks-import" << 'EOF'
#!/bin/bash
# Audiobook Library Database Import
source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
exec "$(audiobooks_python)" "${AUDIOBOOKS_HOME}/library/backend/import_to_db.py" "$@"
EOF
chmod 755 "${BIN_DIR}/audiobooks-import"

# Config viewer
cat > "${BIN_DIR}/audiobooks-config" << 'EOF'
#!/bin/bash
# Show audiobook library configuration
source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
audiobooks_print_config
EOF
chmod 755 "${BIN_DIR}/audiobooks-config"

# Setup Python virtual environment if needed
if [[ ! -d "${LIB_DIR}/library/venv" ]]; then
    echo -e "${BLUE}Setting up Python virtual environment...${NC}"
    python3 -m venv "${LIB_DIR}/library/venv"
    "${LIB_DIR}/library/venv/bin/pip" install --quiet Flask
fi

# Generate SSL certificate if needed
CERT_DIR="${LIB_DIR}/library/certs"
if [[ ! -f "${CERT_DIR}/server.crt" ]]; then
    echo -e "${BLUE}Generating SSL certificate...${NC}"
    mkdir -p "${CERT_DIR}"
    openssl req -x509 -newkey rsa:4096 -sha256 -days 1095 \
        -nodes -keyout "${CERT_DIR}/server.key" -out "${CERT_DIR}/server.crt" \
        -subj "/CN=localhost/O=Audiobooks/C=US" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
        2>/dev/null
    chmod 600 "${CERT_DIR}/server.key"
    chmod 644 "${CERT_DIR}/server.crt"
fi

# Install systemd services
if [[ "$INSTALL_SERVICES" == "true" ]]; then
    echo -e "${BLUE}Installing systemd services...${NC}"

    # API service
    cat > "${SYSTEMD_DIR}/audiobooks-api.service" << EOF
[Unit]
Description=Audiobooks Library API Server
Documentation=https://github.com/greogory/Audiobook-Manager
After=network.target

[Service]
Type=simple
EnvironmentFile=${CONFIG_DIR}/audiobooks.conf
ExecStartPre=/bin/sh -c '! /usr/bin/lsof -i:\${AUDIOBOOKS_API_PORT} >/dev/null 2>&1'
ExecStart=${BIN_DIR}/audiobooks-api
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    # Web service
    cat > "${SYSTEMD_DIR}/audiobooks-web.service" << EOF
[Unit]
Description=Audiobooks Library Web Server (HTTPS)
Documentation=https://github.com/greogory/Audiobook-Manager
After=audiobooks-api.service
Wants=audiobooks-api.service

[Service]
Type=simple
EnvironmentFile=${CONFIG_DIR}/audiobooks.conf
ExecStartPre=/bin/sh -c '! /usr/bin/lsof -i:\${AUDIOBOOKS_WEB_PORT} >/dev/null 2>&1'
ExecStart=${BIN_DIR}/audiobooks-web
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    # Target
    cat > "${SYSTEMD_DIR}/audiobooks.target" << EOF
[Unit]
Description=Audiobooks Library Services
Documentation=https://github.com/greogory/Audiobook-Manager
Wants=audiobooks-api.service audiobooks-web.service

[Install]
WantedBy=multi-user.target
EOF

    # Reload systemd
    systemctl daemon-reload

    echo ""
    echo -e "${YELLOW}To enable services at boot:${NC}"
    echo "  sudo systemctl enable audiobooks-api audiobooks-web"
    echo ""
    echo -e "${YELLOW}To start services now:${NC}"
    echo "  sudo systemctl start audiobooks-api audiobooks-web"
fi

# Create /etc/profile.d script for environment
echo -e "${BLUE}Creating environment profile...${NC}"
cat > /etc/profile.d/audiobooks.sh << 'EOF'
# Audiobook Library Environment
# Source the config loader to get all variables
if [[ -f /usr/local/lib/audiobooks/lib/audiobooks-config.sh ]]; then
    source /usr/local/lib/audiobooks/lib/audiobooks-config.sh
fi
EOF
chmod 644 /etc/profile.d/audiobooks.sh

echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo "Configuration: ${CONFIG_DIR}/audiobooks.conf"
echo "Data directory: ${DATA_DIR}"
echo ""
echo "Commands available:"
echo "  audiobooks-api      - Start API server"
echo "  audiobooks-web      - Start web server"
echo "  audiobooks-scan     - Scan audiobook library"
echo "  audiobooks-import   - Import to database"
echo "  audiobooks-config   - Show configuration"
echo ""
echo "Access the library at: https://localhost:8090"
echo ""
